core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

admin.site.site_header = "We're Upload"
admin.site.site_title = " Upload Portal"
admin.site.index_title = "Welcome To Upload Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('document/', include('upload.urls', namespace='upload')),
    path('', include('pages.urls', namespace='pages')),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from pages.views import HomePageView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home')
]

upload/urls.py
from django.urls import path
from .views import meeting_list, upload_document

app_name = 'upload'

urlpatterns = [
    path('uploads/', meeting_list, name='upload-list'),
    path('add/', upload_document, name='upload'),
]

pages/models.py
from django.db import models

# Create your models here.

upload/models.py
from django.utils import timezone
from django.db import models
from django.utils.translation import gettext_lazy as _


class Upload(models.Model):
    # class Status(models.IntegerChoices):
    #     SPECIAL = 1, 'Special'
    #     REGULAR = 2, 'Regular'

    class STATUS(models.TextChoices):
        SPECIAL = 'SPECIAL', _('Special')
        REGULAR = 'REGULAR', _('Regular')

    description = models.CharField(max_length=255, help_text='Meeting Description')
    document = models.FileField(upload_to='uploads/documents/s/%Y/%m/%d')
    publish = models.DateTimeField(_("Published Date"), blank=True, null=True, default=timezone.now)
    status = models.CharField(verbose_name='Status', choices=STATUS.choices, max_length=20, blank=True, null=True)

    class Meta:
        verbose_name = _('Upload')
        verbose_name_plural = _('Uploads')
        ordering = ['-publish', ]

    def __str__(self):
        return self.description

users/models.py
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    class Meta:
        permissions = [
            ('is_special', 'Special User Status'),
            ('is_regular', 'Regular User Status')
        ]

upload/forms.py
from django.forms import ModelForm
from .models import Upload


class MeetingModelForm(ModelForm):
    class Meta:
        model = Upload
        fields = ['description', 'document', ]

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')

pages/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = 'pages/home.html'

upload/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView
from upload.models import Upload
from .forms import MeetingModelForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


class MeetingPageListView(ListView):
    model = Upload
    paginate_by = 5
    template_name = 'upload/upload_list.html'
    context_object_name = 'meetings'
    queryset = Upload.objects.all()


def meeting_list(request):
    list_upload = Upload.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(list_upload, 10)
    try:
        meetings = paginator.page(page)
    except PageNotAnInteger:
        meetings = paginator.page(1)
    except EmptyPage:
        meetings = paginator.page(paginator.num_pages)
    context = {
        "meetings": meetings,
    }
    return render(request, 'upload/upload_list.html', context)


# def upload_document(request):
#     if request.method == "POST":
#         form = MeetingModelForm(request.POST, request.FILES)
#         documents = request.FILES.getlist('document')
#         if form.is_valid():
#             form.save()
#             for f in documents:
#                 document_instance = Meeting(document=f)
#                 document_instance.save()
#             return redirect('academic_meetings:meeting-list')
#     else:
#         form = MeetingModelForm()
#     context = {
#         'form':form
#     }
#     return render(request, 'meetings/upload_document.html',context)

def upload_document(request):
    if request.method == "POST":
        form = MeetingModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('upload:upload-list')
    else:
        form = MeetingModelForm()
    context = {
        'form': form
    }
    return render(request, 'upload/upload_document.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>We Are Upload</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% tailwind_css %}
    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.3/dist/flowbite.min.css">
    <title>{% block title %}{% endblock title %}</title>

</head>

<body class="bg-green-600 font-serif leading-normal tracking-normal">
{% block nav %}
    {% include 'partials/nav.html' %}
{% endblock nav %}

{% block content %}{% endblock content %}
{% block footer %}{% endblock footer %}


{% comment %} <script src="https://cdn.tailwindcss.com"></script> {% endcomment %}
<script src="https://unpkg.com/flowbite@1.5.3/dist/flowbite.js"></script>
</body>
</html>

theme/templates/pages/home.html
{% extends 'base.html' %}
{% load static %}
{% block nav %}
    <div class="2xl:container 2xl:mx-auto">
        <div class="bg-white dark:bg-gray-800 dark:rounded-none  rounded shadow-lg py-5 px-7 sticky top-0">
            <nav class="flex justify-between">
                <div class="flex items-center space-x-3 lg:pr-16 pr-6">
                    <img class="cursor-pointer dark:bg-white p-1 rounded w-12 h-12"
                         src="https://cnspfbdfpgwplfqfnexb.supabase.co/storage/v1/object/sign/the-upload/static/UMaTLogo.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJ0aGUtdXBsb2FkL3N0YXRpYy9VTWFUTG9nby5qcGciLCJpYXQiOjE2NjYwMDg4OTYsImV4cCI6MTk4MTM2ODg5Nn0.WejdSUdClQv_ks8BLuXegZuKb9qugyBnWIgbfSLyGtg" alt="circle"/>
                    <h2 class="font-normal text-2xl leading-6 text-gray-800 dark:text-white ">
                        <a href="{% url 'pages:home' %}">Upload</a>
                    </h2>
                </div>

                <div class=" flex space-x-5 justify-center  items-center pl-2">
                    <a href="{% url 'upload:upload-list' %}" class="text-gray-700 dark:text-white">Meeting</a>
                    {% if user.is_superuser %}
                        <a href="{% url 'upload:upload' %}" class="text-gray-700 dark:text-white">Add Meetings</a>
                        {% comment %} <a href="{% url 'account_logout' %}" class="dark:text-white">Logout</a>
                        {% endcomment %}
                    {% endif %}
                    {% if user.is_authenticated %}
                        <a href="{% url 'account_logout' %}" class="text-gray-700 dark:text-white">Logout</a>
                    {% else %}
                        <a href="{% url 'account_login' %}" class="text-gray-700 dark:text-white">Login</a>

                    {% endif %}
                    <div class="relative dark:bg-white rounded cursor-pointer focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-800 ">

                        <div class="animate-ping w-1.5 h-1.5 bg-green-600 rounded-full absolute -top-1 -right-1 m-auto duration-200"></div>
                        <div class=" w-1.5 h-1.5 bg-green-600 rounded-full absolute -top-1 -right-1 m-auto shadow-lg"></div>
                    </div>

                </div>
            </nav>

        </div>
    </div>
{% endblock nav %}

{% block content %}
    {% include 'partials/carosuel.html' %}
    {% include 'partials/board.html' %}
{% endblock content %}

theme/templates/partials/board.html
{% load static %}

<h2 class="text-center text-gray-100 text-2xl p-3 m-3">About The Academic Board</h2>
<div class="container mx-auto md:grid md:grid-cols-2 md:gap-2 text-gray-200 p-3 m-3">
    <div class="items-center justify-center p-auto m-auto">
        <section class="flex items-center justify-center">
            <h1 class="text-5xl">The Academic Board</h1>
        </section>
        <p class="items-center content-center text-justify p-3 m-3 text-gray-100 font-normal tex-6xl">
            The Academic Board is the governing body of the University that formulate and enchances the academic
            policies of the University,
            to regulate and approve the programme of studies and examinations held in the University
        </p>
        <div class="relative overflow-x-auto shadow-sm sm:rounded-lg items-center  justify-center w-1/2 m-7 mx-auto rounded">

        </div>
    </div>
    <div>
        <img src="https://cnspfbdfpgwplfqfnexb.supabase.co/storage/v1/object/sign/the-upload/static/conf.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJ0aGUtdXBsb2FkL3N0YXRpYy9jb25mLmpwZyIsImlhdCI6MTY2NjAwODg0MCwiZXhwIjoxOTgxMzY4ODQwfQ.0QGktxF1Gs3-YRlJ_GSJgMo6_ij7Gp2646pVJh-wA_g" class="rounded-sm shadow-lg">
    </div>
</div>
<div class="container mx-auto md:grid md:grid-cols-2 md:gap-2 text-gray-200 p-3 m-3">
    <div>
        <img src="https://cnspfbdfpgwplfqfnexb.supabase.co/storage/v1/object/sign/the-upload/static/meeting_black.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJ0aGUtdXBsb2FkL3N0YXRpYy9tZWV0aW5nX2JsYWNrLmpwZyIsImlhdCI6MTY2NjAwODcyNCwiZXhwIjoxOTgxMzY4NzI0fQ.It4nxjLKYmHDagfMHqOMmMwveHje6iGXILpw4hqkar0" class="rounded-sm shadow-xl">
    </div>
    <div class="items-center justify-center p-auto m-auto">
        <section class="flex items-center justify-center">
            <h1 class="text-4xl items-start">COMPOSITION OF THE ACADEMIC BOARD</h1>
        </section>
        <ul class="list-disc p-3 mx-2 text-gray-100 font-normal tex-6xl not-italic space-y-1">
            <li>The Vice Chancellor</li>
            <li>The Pro Vice Chancellor</li>
            <li>All Deans</li>
            <li>All Heads of Academic Departments and Centres</li>
            <li>Professors</li>
            <li>Senior Members of Council who are not members of the Academic Board in any other capacity</li>
            <li>One member not below the rank of Associate Professor elected from each Faculty by the Senior Members of
                the Faculty.
                Where there are no Senior Members of professorial status, a senior lecturer shall be elected
            </li>
            <li>The Registrar shall be the Secretary to the Board</li>
        </ul>
        <div class="relative overflow-x-auto shadow-sm sm:rounded-lg items-center  justify-center w-1/2 m-7 mx-auto rounded">
        </div>
    </div>

</div>

theme/templates/partials/carosuel.html
{% load static %}
<div id="animation-carousel" class="relative" data-carousel="static">
    <!-- Carousel wrapper -->
    <div class="overflow-hidden relative h-96 rounded-sm sm:h-5/6 xl:h-5/6 2xl:h-5/6">
        <!-- Item 1 -->
        <div class="hidden  duration-30 ease-in-out" data-carousel-item>
            <span class="absolute top-1/2 left-1/2 text-2xl font-semibold text-white -translate-x-1/2 -translate-y-1/2 sm:text-3xl dark:text-gray-800">First Slide</span>
            <img src="https://cnspfbdfpgwplfqfnexb.supabase.co/storage/v1/object/sign/the-upload/static/rm.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJ0aGUtdXBsb2FkL3N0YXRpYy9ybS5qcGciLCJpYXQiOjE2NjYwMDg3ODYsImV4cCI6MTk4MTM2ODc4Nn0.F_cgZXLWsgpAhpuMbaCEmVmmORbZ8oKj8Y2If3i_k8o"
                 class="block absolute top-1/2 left-1/2 w-full -translate-x-1/2 -translate-y-1/2" alt="...">
        </div>
        <!-- Item 2 -->
        <div class="hidden duration-30 ease-in-out" data-carousel-item>
            <img src="https://cnspfbdfpgwplfqfnexb.supabase.co/storage/v1/object/sign/the-upload/static/meeting_blac.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJ0aGUtdXBsb2FkL3N0YXRpYy9tZWV0aW5nX2JsYWMuanBnIiwiaWF0IjoxNjY2MDA4NzE2LCJleHAiOjE5ODEzNjg3MTZ9.UuFfFzttPpHWMKSN6AvRAaf-tiCFDYzyLaKXYxDVI2A"
                 class="block absolute top-1/2 left-1/2 w-full -translate-x-1/2 -translate-y-1/2" alt="...">
        </div>
        <!-- Item 3 -->
        <div class="hidden duration-30 ease-in-out" data-carousel-item>
            <img src="https://cnspfbdfpgwplfqfnexb.supabase.co/storage/v1/object/sign/the-upload/static/meeting.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJ0aGUtdXBsb2FkL3N0YXRpYy9tZWV0aW5nLmpwZyIsImlhdCI6MTY2NjAwODc2MiwiZXhwIjoxOTgxMzY4NzYyfQ.iTKTEod-1Rx5MqfECuDeSIfiPxSQVsDzHEKKdAeWPKw"
                 class="block absolute top-1/2 left-1/2 w-full -translate-x-1/2 -translate-y-1/2" alt="...">
        </div>
    </div>
    <!-- Slider indicators -->
    <div class="flex absolute bottom-5 left-1/2 z-30 space-x-3 -translate-x-1/2">
        <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 1"
                data-carousel-slide-to="0"></button>
        <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 2"
                data-carousel-slide-to="1"></button>
        <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 3"
                data-carousel-slide-to="2"></button>
    </div>
    <!-- Slider controls -->
    <button type="button"
            class="flex absolute top-0 left-0 z-30 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none"
            data-carousel-prev>
<span class="inline-flex justify-center items-center w-8 h-8 rounded-full sm:w-10 sm:h-10 bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
<svg class="w-5 h-5 text-white sm:w-6 sm:h-6 dark:text-gray-800" fill="none" stroke="currentColor" viewBox="0 0 24 24"
     xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                              d="M15 19l-7-7 7-7"></path></svg>
<span class="hidden">Previous</span>
</span>
    </button>
    <button type="button"
            class="flex absolute top-0 right-0 z-30 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none"
            data-carousel-next>
<span class="inline-flex justify-center items-center w-8 h-8 rounded-full sm:w-10 sm:h-10 bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
<svg class="w-5 h-5 text-white sm:w-6 sm:h-6 dark:text-gray-800" fill="none" stroke="currentColor" viewBox="0 0 24 24"
     xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                              d="M9 5l7 7-7 7"></path></svg>
<span class="hidden">Next</span>
</span>
    </button>
</div>

theme/templates/partials/footer.html
<footer class="bg-gray-100 h-20">
    <div class="grid grid-cols-3">
        <div></div>
        <div>We Are Upload</div>
        <div class="text-justify">By: McLean Cofie</div>
    </div>
</footer>

theme/templates/partials/nav.html
{% load static %}
<div class="2xl:container 2xl:mx-auto sm:inset-x-0">
    <div class="bg-white dark:bg-gray-800 dark:rounded-none rounded shadow-lg py-5 px-7">
        <nav class="flex justify-between">
            <div class="flex items-center space-x-3 lg:pr-16 pr-6">
                <img class="cursor-pointer dark:bg-white p-1 rounded w-12 h-12" src="https://cnspfbdfpgwplfqfnexb.supabase.co/storage/v1/object/sign/the-upload/static/UMaTLogo.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJ0aGUtdXBsb2FkL3N0YXRpYy9VTWFUTG9nby5qcGciLCJpYXQiOjE2NjYwMDg4OTYsImV4cCI6MTk4MTM2ODg5Nn0.WejdSUdClQv_ks8BLuXegZuKb9qugyBnWIgbfSLyGtg"
                     alt="circle"/>
                <h2 class="font-normal text-2xl leading-6 text-gray-800 dark:text-white ">
                    <a href="{% url 'pages:home' %}">Upload</a>
                </h2>
            </div>

            <div class=" flex space-x-5 justify-center  items-center pl-2">
                <a href="{% url 'upload:upload-list' %}" class="text-gray-700 dark:text-white">Meeting</a>
                {% if user.is_superuser %}
                    <a href="{% url 'upload:upload' %}" class="text-gray-700 dark:text-white">Add Meetings</a>
                    <a href="{% url 'account_logout' %}" class="text-gray-700 dark:text-white">Logout</a>
                {% endif %}
                {% comment %} {% if user.is_authenticated %}
                    <a href="{% url 'account_logout' %}" class="dark:text-white">Logout</a>
                {% else %}
                    <a href="{% url 'account_login' %}" class="dark:text-white">Login</a>
                    <a href="{% url 'account_signup' %}" class="dark:text-white">SignUp</a>
                {% endif %} {% endcomment %}
                <div class="relative dark:bg-white rounded cursor-pointer focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-800 ">

                    <div class="animate-ping w-1.5 h-1.5 bg-green-600 rounded-full absolute -top-1 -right-1 m-auto duration-200"></div>
                    <div class=" w-1.5 h-1.5 bg-green-600 rounded-full absolute -top-1 -right-1 m-auto shadow-lg"></div>
                </div>

            </div>

            {% comment %}
                <button id="menu" aria-label="open menu"
                        class="focus:outline-none focus:ring-2 focus:ring-gray-600 rounded-md text-gray-800"
                        onclick="sidebarHandler(true)">
                    <img class="icon icon-tabler icon-tabler-menu-2"
                         src="https://tuk-cdn.s3.amazonaws.com/can-uploader/light-with-button-svg10.svg" alt="menu"/>
                </button> {% endcomment %}
        </nav>

    </div>
</div>

theme/templates/partials/table.html
<div class="relative overflow-x-auto shadow-md sm:rounded-lg justify-between w-2/3 mt-6 pt-6 mx-auto  bg-white rounded">
    <h2 class="items-center text-center font-bold text-2xl uppercase justify-evenly mt-2">Meeting Records</h2>
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 p-2 m-2 dark:bg-gray-700 dark:text-gray-400">
        <tr>
            <th scope="col" class="px-6 py-3">
                Description
            </th>
            <th scope="col" class="px-6 py-3">
                Download
            </th>
            <th scope="col" class="px-6 py-3">
                Upload Date
            </th>
        </tr>
        </thead>
        <tbody>
        {% for meeting in meetings %}
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                    {{ meeting.description }}
                </th>
                <td class="px-6 py-4">
                    <a
                            {% comment %} {% if user.is_authenticated %}
                                {% if meeting.status is SPECIAL and perms.users.is_special %}
                                    href="{{ meeting.document.url }}"
                                {% elif meeting.status is REGULAR and perms.users.is_regular %}
                                    href="{{ meeting.document.url }}"
                                {% endif %}
                            {% else %}
                                    href="#"
                            {% endif %} {% endcomment %}
                                    href="{{ meeting.document.url }}"
                                    class="bg-green-500 text-white p-2 rounded hover:underline"
                                    target="_blank">Download</a>
                </td>
                <td class="px-6 py-4">
                    {{ meeting.publish }}
                </td>

            </tr>
        {% endfor %}
        </tbody>

    </table>
    <div class="pagination text-center p-2 m-2 ">
<span class="step-links bg-green-500 p-1 m-1 rounded text-gray-100">
{% if meetings.has_previous %}
    <a href="?page=1">&laquo; first</a>
{% endif %}

    <span class="current">
Page {{ meetings.number }} of {{ meetings.paginator.num_pages }}.
</span>

    {% if meetings.has_next %}
        <a href="?page={{ meetings.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
</span>
    </div>
</div>

theme/templates/partials/table_new.html
<div class="relative pt-6 overflow-x-auto shadow-md sm:rounded-lg justify-between w-2/3 m-7 mx-auto bg-white rounded">
    <table class="table-auto">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 p-2 m-2 dark:bg-gray-700 dark:text-gray-400">
        <tr>
            <th scope="col" class="px-6 py-3">
                Description
            </th>
            <th scope="col" class="px-6 py-3">
                Download
            </th>
            <th scope="col" class="px-6 py-3">
                Upload Date
            </th>
        </tr>
        </thead>
        <tbody>
        {% for meeting in meetings %}
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                    {{ meeting.description }}
                </th>
                <td class="px-6 py-4">
                    <a
                            {% if user.is_authenticated %}
                                {% if meeting.status is SPECIAL and perms.users.is_special %}
                                    href="{{ meeting.document.url }}"
                                {% elif meeting.status is REGULAR and perms.users.is_regular %}
                                    href="{{ meeting.document.url }}"
                                {% endif %}
                            {% else %}
                                    href="#"
                            {% endif %}
                                    href="{{ meeting.document.url }}"
                                    class="bg-green-500 text-white p-2 rounded hover:underline"
                                    target="_blank">Download</a>
                </td>
                <td class="px-6 py-4">
                    {{ meeting.publish }}
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

theme/templates/upload/upload_document.html
{% extends 'base.html' %}
{% load static %}
{% load tailwind_filters %}
{% block content %}
    <div class="pt-6 flex items-center justify-between w-1/2 m-7 mx-auto">
        <div class="flex flex-col lg:flex-row w-full items-start lg:items-center rounded bg-white shadow">
            <div class="w-full  h-auto dark:bg-gray-800 items-center">
                <h2 class="items-center text-center text-2xl uppercase justify-evenly mt-2 mx-auto">Add Meeting
                    Records</h2>
                <form class="m-5" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="bg-green-500 text-white rounded my-2 mt-2 mr-2 p-3">Upload Meeting</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

theme/templates/upload/upload_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    {% include 'partials/table.html' %}
{% endblock content %}